### ISSUE TITLE
Mod portal

### ISSUE THREAD

**Issue by stheid** [PFQNiet/Satisfactorio#56]
First of all: amazing idea, i was also thinking of implementing such a mod never started doing so :heart: 

Are there any plans to bring this mod to the mod-portal? i am quite sure there is a lot of interest in your mod and it would definetly increase visibility.

**Comment by PFQNiet** [comment]
Hey there, thanks for stopping by!

I am certainly planning on bringing this to the mod portal but there's two reasons for delaying:

- Graphics. I can't do them and I'm hoping to find someone who can. 
- Update 4 is coming to Satisfactory in the early months of 2021, so it seems silly to release this mod on the mod-portal when it's going to change substantially so soon.

All being well, I'll be publishing this mod around late February, but if course you're welcome to download one of the releases from here :)

**Comment by stheid** [comment]
hm, i think there will be new versions anyway and i guess there are many people that might be interested in any case, but i also understand the reasoning behind the decision.

Yeah, the graphics are a problem. i think creating a factorio mod is a little outside of fair use :D

But i thought if you publish it you might also have a better chance to find contributers. In any case: keep up the good work :)
