### ISSUE TITLE
Trying to tame a second Doggo causes a crash

### ISSUE THREAD

**Issue by Robeja** [PFQNiet/Satisfactorio#75]
Hello,

It's me again.

When trying to tame a second Lizard Doggo, this error appears:

> The mod Satisfactorio [BETA] (0.8.5) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event Satisfactorio::on_ai_command_completed (ID 116)
> Given object is not lua entity.
> stack traceback:
> 	[C]: in function 'set_command'
> 	__Satisfactorio__/scripts/creatures/lizard-doggo.lua:175: in function 'eatFood'
> 	__Satisfactorio__/scripts/creatures/lizard-doggo.lua:267: in function 'handler'
> 	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
> 	

I happens when a Paleberry is dropped onto the ground (with Z key) then the Doggo tries to eat it.

**Attachment**
I'm attaching a save file: s049.zip
[s049.zip](https://github.com/PFQNiet/Satisfactorio/files/6795266/s049.zip)

**Mods**
No other mods are being used
Mod version: 0.8.5

**To Reproduce**
Load the save, there is a tamed doggo already trapped on a pen near the hub (NorthWest), and I'm trying to tame another one which is nearby (SouthWest).

**Expected behavior**
The doggo doesn't want to crash when trying to eat the food.
He is a good boy.

**Additional info**
I want to make kennels, for the doggos to bring me slugs...

Kind regards,
   Robeja.

**Comment by PFQNiet** [comment]
Thanks again, was an error in refactoring that caused the issue :)
