### ISSUE TITLE
Beryl nut tree[ERROR]

### ISSUE THREAD

**Issue by Ravage666** [PFQNiet/Satisfactorio#91]
Describe the bug
Character getting stuck on Beryl nut tree

To Reproduce

1-Stant on the Beryl nut tree
2-Left click to harvest

 
Mod
Squeak Through

Expected behavior

Screenshots

Error message
No Crash

Additional info

**Comment by PFQNiet** [comment]
Just to confirm, this happens if you stand *very close* to the tree when harvesting it? Does it also apply to Paleberries?

**Comment by Ravage666** [comment]
Yes affect both with or without Squeak Through

very close to the center or if you walk towards it
