### ISSUE TITLE
Technology Pack

### ISSUE THREAD

**Issue by MigarisS** [PFQNiet/Satisfactorio#94]
**Describe the bug**
If you start the research and at that moment put the constructor with the conveyor, then the technology package will come out and the research will not be able to continue.

**To Reproduce**
1. Start your research
2. Put the constructor above the warehouse with wire
3. Move the conveyor from the constructor up
4. Technology package leaves the constructor

**Expected behavior**
The error is raised only in a certain place. The reason is not known to me. Can't describe more.

**Video**
https://youtu.be/9i7eLB9FE20 
I apologize for the lags, I have a weak laptop and I don’t even know how the video could be recorded

Save for reproduce [Satis-BUG.zip](https://github.com/PFQNiet/Satisfactorio/files/9897048/Satis-BUG.zip)

**Comment by PFQNiet** [comment]
Incredible! So what's happening here is that you are placing the building at `(0,0)`, which is where the invisible lab that does MAM research gets placed. This confuses the belt loaders and it does indeed unload the "science pack" from the invisible lab.

The workaround for now is just "don't build at `(0,0)`" -- given that the game starts with the player having to go find iron some distance away, it's actually remarkably unlikely to build in this exact position, but as you've shown it is not impossible. I may need to do something like create a separate surface for the hidden lab, just to make extra sure that nothing can interfere with it.

I will work on a fix when I have the opportunity, but I can't promise when that will be as I have other things going on IRL. But thank you for finding and reporting this issue.

**Comment by PFQNiet** [comment]
It will be fixed in the next release, but again no real knowing when that will be. If you wish to patch this yourself, follow these steps:

- From the mod file (usually in `%APPDATA%/Factorio/mods`) extract the file `prototypes/technology.lua`
- In the `local lab = { ... }` block, make these changes:

```diff
- collision_box = {{-1.3,-1.3},{1.3,1.3}},
- collision_mask = {},
- selection_box = {{-1.5,-1.5},{1.5,1.5}},

+ collision_box = {{0,0},{0,0}},
+ collision_mask = {},
+ selection_box = {{0,0},{0,0}},
```
Save, and put the file back into the ZIP where it came from. This will patch the issue.
